#!/usr/bin/env python3
"""
purge_mock_questions.py — Find and deactivate mock/placeholder question documents.

Mock questions generated by _mock_questions() / _generate_mock_options() in
backend/app/services/ai_service.py have a recognizable fingerprint:
  - question_text matches patterns like:
      "Which statement best describes a key concept from '<topic>'..."
      "[<course_code> | Week <N> | Q<N>] Given a standard <topic> setup..."
  - explanation contains:
      "Option A correctly identifies the primary principle"
      "Use the relevant formula/operation chain for"
  - options values contain phrases like:
      "A fundamental statement describing the core idea of"
      "A nuanced implication or typical exception related to"
      "An indirect consequence derived from ... theory"

Usage:
    python backend/scripts/purge_mock_questions.py              # dry-run
    python backend/scripts/purge_mock_questions.py --apply      # actually deactivate
"""

import argparse
import asyncio
import json
import logging
import re
import sys
from datetime import datetime
from pathlib import Path

# Add backend root to sys.path so we can import app modules
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from bson import ObjectId

from app.core.database import questions_col, pdfs_col, pdf_jobs_col
from app.core.config import settings

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)
logger = logging.getLogger("purge_mock_questions")

# ── Fingerprint patterns ───────────────────────────────────────────────────

QUESTION_TEXT_PATTERNS = [
    re.compile(
        r"Which statement best describes a key concept from\s+'.*?'\s+as covered in",
        re.IGNORECASE,
    ),
    re.compile(
        r"Given a standard\s+.*?\s+setup, compute the correct result",
        re.IGNORECASE,
    ),
]

EXPLANATION_PATTERNS = [
    re.compile(
        r"Option A correctly identifies the primary principle",
        re.IGNORECASE,
    ),
    re.compile(
        r"Use the relevant formula/operation chain for",
        re.IGNORECASE,
    ),
]

OPTIONS_PHRASES = [
    "A fundamental statement describing the core idea of",
    "A nuanced implication or typical exception related to",
    "A secondary characteristic observed in",
    "An indirect consequence derived from",
    "An unrelated or incorrect statement not supported by",
]


def _matches_fingerprint(doc: dict) -> bool:
    """Check if a question document matches the mock fingerprint."""
    question_text = (doc.get("question_text") or "")
    explanation = (doc.get("explanation") or "")
    options = (doc.get("options") or {})
    options_text = " ".join(str(v) for v in options.values())

    # Match question_text
    if any(p.search(question_text) for p in QUESTION_TEXT_PATTERNS):
        return True

    # Match explanation
    if any(p.search(explanation) for p in EXPLANATION_PATTERNS):
        return True

    # Match options phrases
    if any(phrase in options_text for phrase in OPTIONS_PHRASES):
        return True

    return False


async def find_mock_questions() -> list[dict]:
    """Find all question documents matching mock fingerprint patterns.
    Uses server-side regex filtering on indexed patterns, then applies
    the option-phrase check in Python as a final pass.
    """
    # Build server-side $or filter — regex on question_text and explanation
    or_filters = []

    for pattern in QUESTION_TEXT_PATTERNS:
        or_filters.append({"question_text": {"$regex": pattern.pattern, "$options": "i"}})

    for pattern in EXPLANATION_PATTERNS:
        or_filters.append({"explanation": {"$regex": pattern.pattern, "$options": "i"}})

    # Also match by options field since we can't easily do sub-field regex server-side
    # We'll fetch candidates via the above filters and then check options in Python.
    # Also include source="mock" docs for forward compatibility.
    or_filters.append({"source": "mock"})

    query = {"$or": or_filters} if or_filters else {}

    candidates = await questions_col().find(query).to_list(None)

    # Apply full fingerprint check (including options phrases) in Python
    mock_docs = [doc for doc in candidates if _matches_fingerprint(doc)]

    return mock_docs


def _group_report(mock_docs: list[dict]) -> dict:
    """Group mock docs by (course_id, week_number) and return counts."""
    groups: dict[tuple[str, int], dict] = {}
    for doc in mock_docs:
        key = (doc.get("course_id", "unknown"), doc.get("week_number", 0))
        if key not in groups:
            groups[key] = {
                "course_id": key[0],
                "week_number": key[1],
                "count": 0,
                "ids": [],
            }
        groups[key]["count"] += 1
        groups[key]["ids"].append(str(doc["_id"]))
    return groups


async def get_active_counts_by_pair(mock_pairs: list[tuple[str, int]]) -> dict:
    """For each (course_id, week_number), return the count of active (non-mock) questions."""
    result = {}
    for course_id, week_number in mock_pairs:
        total_active = await questions_col().count_documents({
            "course_id": course_id,
            "week_number": week_number,
            "is_active": True,
            "source": {"$ne": "mock"},
        })
        result[(course_id, week_number)] = total_active
    return result


async def requeue_source_pdf(course_id: str, week_number: int) -> None:
    """Reset the pdf_jobs entry for the given (course_id, week_number) to pending."""
    pdf_doc = await pdfs_col().find_one({
        "course_id": course_id,
        "week_number": week_number,
    })
    if not pdf_doc:
        logger.warning(
            "No PDF document found for course_id=%s week_number=%s — cannot requeue",
            course_id, week_number,
        )
        return

    pdf_id = str(pdf_doc["_id"])

    # Reset the pdf_jobs entry so job_worker.py picks it up
    result = await pdf_jobs_col().update_one(
        {"pdf_id": pdf_id, "course_id": course_id},
        {"$set": {
            "status": "pending",
            "attempt_count": 0,
            "last_error": None,
            "next_attempt_at": None,
            "updated_at": datetime.utcnow(),
        }},
    )

    if result.matched_count == 0:
        logger.warning(
            "No pdf_jobs entry found for pdf_id=%s course_id=%s — cannot requeue",
            pdf_id, course_id,
        )
    else:
        logger.info(
            "Requeued pdf_jobs for course_id=%s week_number=%s (pdf_id=%s)",
            course_id, week_number, pdf_id,
        )


async def main(apply: bool = False) -> None:
    """Run the purge script."""
    logger.info("Starting mock question purge (apply=%s)", apply)

    mock_docs = await find_mock_questions()
    total_mock = len(mock_docs)
    logger.info("Found %d mock question(s) total", total_mock)

    if total_mock == 0:
        logger.info("No mock questions found — nothing to do.")
        return

    groups = _group_report(mock_docs)

    # ── Print report ───────────────────────────────────────────────────
    print("\n" + "=" * 72)
    print("  MOCK QUESTION PURGE REPORT  (dry-run mode)" if not apply else
          "  MOCK QUESTION PURGE REPORT  (--apply mode)")
    print("=" * 72)

    grand_total = 0
    sorted_keys = sorted(groups.keys(), key=lambda k: (k[0] or "", k[1] or 0))
    for key in sorted_keys:
        g = groups[key]
        grand_total += g["count"]
        print(f"\n  Course: {g['course_id']}  |  Week: {g['week_number']}")
        print(f"  Mock questions found: {g['count']}")
        print(f"  IDs: {', '.join(g['ids'][:5])}{'...' if len(g['ids']) > 5 else ''}")

    print(f"\n  {'─' * 50}")
    print(f"  TOTAL mock questions: {grand_total}")
    print(f"  {'─' * 50}")

    if not apply:
        print("\n  DRY-RUN — no changes made.")
        print(f"  Run with --apply to deactivate these questions.\n")
        return

    # ── Apply: deactivate ──────────────────────────────────────────────
    print("\n  Applying deactivation...")
    deactivated_count = 0
    affected_ids = []

    for key in sorted_keys:
        g = groups[key]
        qids = g["ids"]
        valid_oids = [ObjectId(qid) for qid in qids if ObjectId.is_valid(qid)]

        if valid_oids:
            result = await questions_col().update_many(
                {"_id": {"$in": valid_oids}},
                {"$set": {"is_active": False, "updated_at": datetime.utcnow()}},
            )
            deactivated_count += result.modified_count
            affected_ids.append({
                "course_id": g["course_id"],
                "week_number": g["week_number"],
                "deactivated": len(valid_oids),
            })

    print(f"\n  Deactivated {deactivated_count} question(s)")

    # ── Check for empty pairs & requeue PDFs ────────────────────────────
    mock_pairs = [(g["course_id"], g["week_number"]) for g in groups.values()]
    active_counts = await get_active_counts_by_pair(mock_pairs)

    requeued = []
    for course_id, week_number in mock_pairs:
        active_count = active_counts.get((course_id, week_number), 0)
        logger.info(
            "After deactivation: course_id=%s week_number=%s has %d active question(s)",
            course_id, week_number, active_count,
        )
        if active_count == 0:
            print(f"\n  ⚠  course_id={course_id} week={week_number}: ZERO active questions remaining — requeuing PDF...")
            await requeue_source_pdf(course_id, week_number)
            requeued.append({"course_id": course_id, "week_number": week_number})

    # ── Persist report ──────────────────────────────────────────────────
    report = {
        "ran_at": datetime.utcnow().isoformat(),
        "total_deactivated": deactivated_count,
        "affected_pairs": affected_ids,
        "requeued_pairs": requeued,
    }

    report_path = Path(__file__).resolve().parent / "mock_purge_report.json"
    with open(report_path, "w") as f:
        json.dump(report, f, indent=2, default=str)
    logger.info("Report written to %s", report_path)

    print(f"\n  Report saved to: {report_path}")
    if requeued:
        print(f"  Requeued {len(requeued)} PDF(s) for reprocessing via job_worker.py")
    print()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Find and deactivate mock/placeholder question documents.",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually apply changes (default: dry-run)",
    )
    args = parser.parse_args()

    asyncio.run(main(apply=args.apply))
